const NOTES = ['A0', 'B0', 
'C1', 'C_1', 'D1', 'D_1', 'E1', 'F1', 'F_1', 'G1', 'G_1', 'A1', 'A_1', 'B1',
'C2', 'C_2', 'D2', 'D_2', 'E2', 'F2', 'F_2', 'G2', 'G_2', 'A2', 'A_2', 'B2',
'C3', 'C_3', 'D3', 'D_3', 'E3', 'F3', 'F_3', 'G3', 'G_3', 'A3', 'A_3', 'B3',
'C4', 'C_4', 'D4', 'D_4', 'E4', 'F4', 'F_4', 'G4', 'G_4', 'A4', 'A_4', 'B4',
'C5', 'C_5', 'D5', 'D_5', 'E5', 'F5', 'F_5', 'G5', 'G_5', 'A5', 'A_5', 'B5',
'C6', 'C_6', 'D6', 'D_6', 'E6', 'F6', 'F_6', 'G6', 'G_6', 'A6', 'A_6', 'B6',
'C7', 'C_7', 'D7', 'D_7', 'E7', 'F7', 'F_7', 'G7', 'G_7', 'A7', 'A_7', 'B7',
'C8', ];

const VALID_BLACK_KEYS = ['s', 'd', 'g', 'h', 'j', '2', '3', '5', '6', '7'];
const VALID_WHITE_KEYS = ['z', 'x', 'c', 'v', 'b', 'n', 'm', 'q', 'w', 'e', 'r', 't', 'y', 'u'];
const VALID_KEYS = [...VALID_BLACK_KEYS, ...VALID_WHITE_KEYS];
const KEY_TO_NOTE = {
    z: 'C3',
    s: 'C_3', 
    x: 'D3',
    d: 'D_3',
    c: 'E3', 
    v: 'F3',
    g: 'F_3',
    b: 'G3',
    h: 'G_3',
    n: 'A3',
    j: 'A_3',
    m: 'B3',
    q: 'C4',
    2: 'C_4',
    w: 'D4',
    3: 'D_4', 
    e: 'E4',
    r: 'F4',
    5: 'F_4', 
    t: 'G4',
    6: 'G_4',
    y: 'A4',
    7: 'A_4',
    u: 'B4',
}

const NOTE_TO_KEY = {
    C3: 'z',
    C_3: 's',
    D3: 'x',
    D_3: 'd',
    E3: 'c',
    F3: 'v',
    F_3: 'g',
    G3: 'b',
    G_3 : 'h',
    A3: 'n',
    A_3: 'j',
    B3: 'm',
    C4: 'q',
    C_4: '2',
    D4: 'w',
    D_4: '3',
    E4: 'e',
    F4: 'r',
    F_4: '5',
    G4: 't',
    G_4 : '6',
    A4: 'y',
    A_4: '7',
    B4: 'u',
}

export { VALID_KEYS, NOTES , KEY_TO_NOTE, NOTE_TO_KEY};